#!/usr/bin/env ruby

$LOAD_PATH.unshift(File.dirname(__FILE__))

require 'beats1'
require 'beats1/engage'

begin
  Beats1::Engage.new.begin
rescue StandardError => err
  puts err
  sleep 10
  retry
end