#!/usr/bin/env ruby

$LOAD_PATH.unshift(File.dirname(__FILE__))

require 'beats1'
require 'rufus-scheduler'

scheduler = Rufus::Scheduler.new

Beats1::Actions.refresh_last_tweet

scheduler.every '15s', overlap: false do
  Beats1::Actions.update
end

scheduler.every '10s', overlap: false do
  Beats1::Actions.refresh_current_program
end

scheduler.every '120s', overlap: false do
  Beats1::Actions.refresh_last_tweet
end

scheduler.join